/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryScore = IDL.Record({
  'maxScore' : IDL.Nat,
  'score' : IDL.Nat,
  'category' : IDL.Text,
});
export const Evaluation = IDL.Record({
  'id' : IDL.Nat,
  'weaknesses' : IDL.Vec(IDL.Text),
  'improvementSuggestions' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'scores' : IDL.Vec(CategoryScore),
  'createdAt' : IDL.Int,
  'maxTotalScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'summary' : IDL.Text,
  'edgeCases' : IDL.Vec(IDL.Text),
  'projectId' : IDL.Nat,
  'efficiencySuggestions' : IDL.Vec(IDL.Text),
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'evaluated' : IDL.Null,
    'pending' : IDL.Null,
    'evaluating' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'title' : IDL.Text,
  'expectedOutput' : IDL.Text,
  'userId' : IDL.Principal,
  'blobIds' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'purpose' : IDL.Text,
  'techStack' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllEvaluations' : IDL.Func([], [IDL.Vec(Evaluation)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvaluation' : IDL.Func([IDL.Nat], [IDL.Opt(Evaluation)], ['query']),
  'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerEvaluation' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryScore = IDL.Record({
    'maxScore' : IDL.Nat,
    'score' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Evaluation = IDL.Record({
    'id' : IDL.Nat,
    'weaknesses' : IDL.Vec(IDL.Text),
    'improvementSuggestions' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'scores' : IDL.Vec(CategoryScore),
    'createdAt' : IDL.Int,
    'maxTotalScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'summary' : IDL.Text,
    'edgeCases' : IDL.Vec(IDL.Text),
    'projectId' : IDL.Nat,
    'efficiencySuggestions' : IDL.Vec(IDL.Text),
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'evaluated' : IDL.Null,
      'pending' : IDL.Null,
      'evaluating' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'title' : IDL.Text,
    'expectedOutput' : IDL.Text,
    'userId' : IDL.Principal,
    'blobIds' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'purpose' : IDL.Text,
    'techStack' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllEvaluations' : IDL.Func([], [IDL.Vec(Evaluation)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvaluation' : IDL.Func([IDL.Nat], [IDL.Opt(Evaluation)], ['query']),
    'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerEvaluation' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };